### ISSUE TITLE
Always show Keystone count

### ISSUE THREAD

**Issue by SiriusAshling** [sparkle-preference/OriWotwRandomizerClient#100]
So you don't have to walk to doors and then be surprised

**Comment by Foopyo** [comment]
Having a way to show gorlek ores count and spirit light count (maybe in a ALT+ command, not necessary always of screen) would also be super useful.

**Comment by SiriusAshling** [comment]
The Inventory screen shows Gorlek Ore and Spirit Light, you can always check there

**Comment by toadettexmushina** [comment]
True, but if you're adding a command to show keystone count, may as well show all the consumables.

**Comment by SiriusAshling** [comment]
I agree it could make sense on a command, but I was simply thinking of showing the keystones using the in-game ui, that way it would be seemless and intuitive without having to explain and bind another command

**Comment by MunWolf** [comment]
Added in https://github.com/sparkle-preference/OriWotwRandomizerClient/commit/ca88e8792bfbac3b9345b3a2e891dee29d29449a
