### ISSUE TITLE
Losing controls when finishing a dialogue

### ISSUE THREAD

**Issue by Foopyo** [sparkle-preference/OriWotwRandomizerClient#101]
Textboxes happening when collecting an item advance dialogues when they are appearing. If one of them close a non-shop dialogue, the game won't give you your control back.
It can be easily reproduce by adding `3|2|6|Blazzze|instant` to your seed and pressing ctrl+alt+1 while you are speaking to an NPC.

Here is an example of it happening with Tuley's branch inpection dialogue being interupted by getting a keystone from Opher.
https://user-images.githubusercontent.com/25066858/111305547-60d85880-8657-11eb-8b6a-13a05b9d9dd6.mp4

**Comment by MunWolf** [comment]
Fixed in https://github.com/sparkle-preference/OriWotwRandomizerClient/commit/5755256cecb263020c5f86f140e50f9da708b21a
