### ISSUE TITLE
Hammer shockwave upgrade not working

### ISSUE THREAD

**Issue by Zekava** [sparkle-preference/OriWotwRandomizerClient#105]
Got the hammer, immediately went and got the shockwave upgrade at Opher, and when I do the dive attack, there is no shockwave. This isn't a _complete_ deal breaker but that's pretty much my favorite move in the game, so this feels pretty bad. Attached is my seed, zipped.

[Initial.zip](https://github.com/sparkle-preference/OriWotwRandomizerClient/files/6291056/Initial.zip)

**Comment by SiriusAshling** [comment]
I can reproduce (Hammer is on Dash Tree)
This seems to extend to the other weapon upgrades as well
Minimal reproduction seed: [shockwave_bug.zip](https://github.com/sparkle-preference/OriWotwRandomizerClient/files/6291593/shockwave_bug.zip)

**Comment by sparkle-preference** [comment]
fixed in 0.12.7
