### ISSUE TITLE
East Pools TP underwater with random spawn

### ISSUE THREAD

**Issue by Foopyo** [sparkle-preference/OriWotwRandomizerClient#114]
If your initial spawn is at the East Pools teleport (random spawn), it will be underwater. It's especially annoying when you spawn there without clean water.

[seed_8.zip](https://github.com/sparkle-preference/OriWotwRandomizerClient/files/6604336/seed_8.zip)

**Comment by SiriusAshling** [comment]
fixed by 6aa66a85478beec26e1d43fbc33d9b82a949df3c
