### ISSUE TITLE
[Webgen] header variables

### ISSUE THREAD

**Issue by SiriusAshling** [sparkle-preference/OriWotwRandomizerClient#124]
Currently only one header has a variable: Black market, where you can enable "cheap".
See [the header docs](https://docs.google.com/document/d/1IR1DHnbtO8rydCLEgFh-yp3iRkzZbFAG-EmR5hxrfmU/edit#heading=h.z2gmgfo0sycl) for parameter documentation.

**Comment by timoschwarzer** [comment]
Superseded by https://github.com/ori-rando/wotw-server/issues/10
