### ISSUE TITLE
In-game map improvements

### ISSUE THREAD

**Issue by timoschwarzer** [sparkle-preference/OriWotwRandomizerClient#150]
- [x] Remove the world map
- [x] Allow to zoom out further
- [ ] Fast-pan the map when using right stick

**Comment by timoschwarzer** [comment]
There's an "Enable Worldmap" setting that does exactly that in the debug menu on page 1 (top right). We can probably just use that.

**Comment by MunWolf** [comment]
@timoschwarzer is the panning a problem with the zoom out? I can look into this if it is still desired.

**Comment by timoschwarzer** [comment]
nah, not really :D
