### ISSUE TITLE
Add dots to map based on where players are.

### ISSUE THREAD

**Issue by MunWolf** [sparkle-preference/OriWotwRandomizerClient#151]
As an early win before we add #102 (since its taking a long time).
We could add dots to the map that represent where the players on your team are currently, this will improve the coop experience.

**Comment by MunWolf** [comment]
The client side work for this is pretty much done, just waiting on the server side API
instead of dots will be using actual icons.

**Comment by timoschwarzer** [comment]
WHOOOPWHOOOOOP LETZZZZZZ GOOOOOOOOOOOOOOOO ORIHYPE ORIHYPE ORIHYPE ORIHYPE ORIHYPE ORIHYPE ORIHYPE ORIHYPE ORIHYPE ORIHYPE ORIHYPE ORIHYPE ORIHYPE ORIHYPE ORIHYPE ORIHYPE ORIHYPE ORIHYPE ORIHYPE
