### ISSUE TITLE
Ctrl+Alt+Alpha on azerty keyboard

### ISSUE THREAD

**Issue by Foopyo** [sparkle-preference/OriWotwRandomizerClient#153]
The Ctrl+Alt+1/2/3/4/5 commands aren't working as intended on AZERTY keyboards: you need to press Ctrl+Alt+Shift+1/2/3/4/5 instead.

**Comment by timoschwarzer** [comment]
Seems to happen with the new native keybindings, too

**Comment by Foopyo** [comment]
Using a US layout doesn't change anything.

**Comment by MunWolf** [comment]
This was fixed by us not using AHK for bindings anymore.
