### ISSUE TITLE
Same seed result in different item placement 

### ISSUE THREAD

**Issue by Foopyo** [sparkle-preference/OriWotwRandomizerClient#156]
When generating a World Tour seed with webgen, giving the same seed to the generator will result in slightly different item placement.
These seeds were generated with the default settings with the seed `Hey I'm a bug!` and with World Tour selected. these seeds don't even have the same number of relics (they have 9, 9, 11 and 8 relics respectively)
[seeds.zip](https://github.com/sparkle-preference/OriWotwRandomizerClient/files/7194817/seeds.zip)

Some headers cause the same behavior. With the default settings, enable all headers beside Bonus Items and the item placement should be different even when using the same seed.

Something to add is that I wasn't able to replicate this issue by generating locally with rustgen, which I compiled the 1st of September from the Kii branch.

**Comment by SiriusAshling** [comment]
Closed by c9a7d865e442f5938f3b05f3bd6eafc3fa06e08c
