### ISSUE TITLE
Bingo Logic

### ISSUE THREAD

**Issue by toadettexmushina** [sparkle-preference/OriWotwRandomizerClient#169]
Create logic for discovery bingo (and maybe regular bingo too)
Have easier goals on starting squares (no more it's 30 mins in and you go straight from 2 goals visible to 21 goals visible)
Have bingo able to read the seed so goals can be tailored to random spawn locations, as well as removing/adjusting goals already (partially) completed by headers (ie open mode, no combat)

**Comment by timoschwarzer** [comment]
@toadettexmushina please open that issue on https://github.com/ori-rando/wotw-server :)
