### ISSUE TITLE
Shop Icons

### ISSUE THREAD

**Issue by toadettexmushina** [sparkle-preference/OriWotwRandomizerClient#170]
Changing shop icons to reflect what's being sold
Making appropriate icons for pickups that don't already have one

**Comment by SiriusAshling** [comment]
Coverage:

- [ ] Spirit Light: in-game, needs to be exposed to the command
- [ ] Resources: in-game, needs to be exposed to the command
- [ ] Abilities: in-game, needs to be exposed to the command (only missing Water Breath from the vanilla shop icons)
- [x] Shards
- [ ] Teleporters: in-game, needs to be exposed to the command
- [ ] Messages: in-game, needs to be exposed to the command (The text bubble quest icon could work)
- [ ] Clean Water: needs custom icon
- [ ] Bonus Items & Upgrades: needs custom icon
- [ ] Relics: needs custom icon

**Comment by toadettexmushina** [comment]
relics could use the eyestone map icon - it's kinda cool looking, and the actual eyestones on the map have long since been replaced by keystones

**Comment by SiriusAshling** [comment]
good idea

**Comment by MunWolf** [comment]
Clean water icon could be the depracated water breath shard

**Comment by SiriusAshling** [comment]
Hm maybe. It doesn't actually show water though.
Maybe we just include the Ori 1 water icon as a file?

**Comment by toadettexmushina** [comment]
For hints, I like the distance travelled icon (looks like a map), but there's also that question mark icon. If we want to get fancy though, I can make custom ones combining the appropriate skills.

The Ori 1 clean water icon is probably our best bet, the watermill icon is not super obvious. There's also the ori 1 water breath icon, makes it look like ori is swimming.

Maybe use a different keystone texture for the black market? There are already a few different ones in the game anyway.

For Bonus Items, I'm thinking some combination of whatever unused icons we can find, some of the ori 1 ability tree icons, and maybe some custom stuff if needed, I'll make a list.

**Comment by SiriusAshling** [comment]
Most of the Bonus stuff is like Efficiencies, so probably a symbol representing Efficiency (energy-) that's overlayed with all the icons it boosts would be good, and then similarly for other upgrades

**Comment by toadettexmushina** [comment]
[
![bowEff](https://user-images.githubusercontent.com/23561609/134797039-f24ea730-b1ad-45a3-a272-6ad9d751246a.png)
![EnergyRegen](https://user-images.githubusercontent.com/23561609/134797041-d139692c-6e86-4f35-ac39-296f4d9ef594.png)
![HealthRegen](https://user-images.githubusercontent.com/23561609/134797042-7f419f34-1cb2-472a-8418-78223fe5b75b.png)
![jumpgrade](https://user-images.githubusercontent.com/23561609/134797043-d9673454-f88a-443d-990a-2faff3f75fa4.png)
](url)

**Comment by toadettexmushina** [comment]
okay, that should be everything, they're all posted in the icons thread. lmk if we need anything else :orinom:

**Comment by timoschwarzer** [comment]
Created a repository for additional assets such as the icons. https://github.com/ori-rando/assets

Please put them in the icons directory oriHug
