### ISSUE TITLE
Custom wheels don't remember active button

### ISSUE THREAD

**Issue by timoschwarzer** [sparkle-preference/OriWotwRandomizerClient#171]
When switching between custom wheels (e.g. the Next button), it always selects the top wheel item. This is annoying when using a controller, because you always need to move the left stick a little bit to make it snap back to the wheel item you're currently pointing to.

**Comment by MunWolf** [comment]
Fixed in https://github.com/sparkle-preference/OriWotwRandomizerClient/commit/c8beeb8b0282c7a9270a06827fdd8035ff8fb61d
