### ISSUE TITLE
Header configuration options

### ISSUE THREAD

**Issue by sparkle-preference** [sparkle-preference/OriWotwRandomizerClient#61]
we want a way for a header to specify one or more config variables that show up in the UI. probably write them to ubervalues? maybe define ranges...

**Comment by MunWolf** [comment]
Could add it as commandline parameters to the rust gen.
`!parameter starting_keystones int range 0 5 default 5`
something like this
and then you pass it to the seedgen `-params starting_keystones=2` or something similar
