### ISSUE TITLE
Manual for beginners

### ISSUE THREAD

**Issue by Foopyo** [sparkle-preference/OriWotwRandomizerClient#68]
Make a file with informations for beginners. This should include:

1. Ingame shortcut list (alt+p and all)
2. Explanation on what techniques are added to each difficulties (for gorlek it would be sentry jumps, shuriken break, weapon air stalling, triple jump...)
3. Ressources to learn all glitches and speedrun techniques required for the randomizer
4. Randomizer new feature in comparison to the vanilla game

**Comment by MunWolf** [comment]
We could even add this to the wiki on this github page, though I would like to add some ingame way to see the shortcuts.

**Comment by toadettexmushina** [comment]
WIP list of tricks and glitches sorted by difficulty
https://docs.google.com/document/d/16tI8kLDE3TvCDc8RQut95jYTVP2j4TyJ0rzaMBir88I/

**Comment by Foopyo** [comment]
WIP version on my fork.
You can help with fixing the wiki by editing this [document ](https://docs.google.com/document/d/1hX-OWfF3tua5vxb51VbY5bNFzTFhWhDY6hXkC0l1rRE/edit?usp=sharing) (you need to send me your mail first)
