### ISSUE TITLE
Reducing grenade energy cost

### ISSUE THREAD

**Issue by Foopyo** [sparkle-preference/OriWotwRandomizerClient#74]
Grenade is seen as a movement option and since using it cost energy, you might run out of energy especialy when you need it in the early game.

**Comment by MunWolf** [comment]
This is taken into account during seedgen, it generates enough energy that you should be able to progress.
And if you have access to glades you can buy the upgrade to lower its cost.
Closing as a won't fix.

**Comment by Foopyo** [comment]
[yes.zip](https://github.com/sparkle-preference/OriWotwRandomizerClient/files/5855327/yes.zip)
It came from this seed.
- You spawn with djump+light burst and it's your only movement option for a while.
- You can access Glades early on but you won't have enough SL to buy the upgrade
- You're supposed to find Grapple which help with the movement but I personaly missed this pickup.
- You also won't find sword/hammer until way later so you need to break walls and combat enemies by using grenade (you do find bow but the problem is pretty much the same since you'll use energy to kill them and won't have a lot when you need grenade for movement)
- I needed to abuse the respawn system multiple times so I'll be refilled mana, especially when I was outside Wellspring

> This is taken into account during seedgen, it generates enough energy that you should be able to progress
I don't know _how_ it's taken into account but if the logic think you'll get the perfect routing and think you'll miss absolutely no grenade shot, it's probably a bit extreme for gorlek difficulty.
