### ISSUE TITLE
Seedgen doesn't work

### ISSUE THREAD

**Issue by Foopyo** [sparkle-preference/OriWotwRandomizerClient#75]
There is an unhandled exception when generating some seeds. Got it with the seed "rip la derniere chance". The seed gen didn't retried to generate this seed.
![javaw_2021-01-22_01-02-40](https://user-images.githubusercontent.com/25066858/105427560-ba229d80-5c4d-11eb-89d6-f8bf6cb5b840.png)

**Comment by MunWolf** [comment]
This is a won't fix, even if this is still an issue we are throwing away the javagen.
