### ISSUE TITLE
Adding requirement for weapon in Depths

### ISSUE THREAD

**Issue by Foopyo** [sparkle-preference/OriWotwRandomizerClient#76]
In this seed, you are supposed to enter Depths using the TP in order to find Marsh TP.
You'll get flash in the area which fulfil the DepthsLight requirement but you'll need to pick this specific item in all of Depths in order to progresss: `UpperDepths.RightHealthKS`. 
You won't have any way to use fireflies or break energy cristal so you'll most likely need to teleport back to the teleporter multiple time to get a refill.
Since you can't break energy cristal, It's likely to cause a softlockable path if the logic think you'll be able to access one pickup but it's actualy too far away from an energy refill.

[degage_sword.zip](https://github.com/sparkle-preference/OriWotwRandomizerClient/files/5855402/degage_sword.zip)

**Comment by MunWolf** [comment]
The logic counts energy for flash and refills from checkpoints and teleporters, it is not possible for it to generate a softlockable path.
All pickups you need to get are easily reachable with the energy refill provided.

Closing
