### ISSUE TITLE
Open the UpperWastes keydoor from behind

### ISSUE THREAD

**Issue by SiriusAshling** [sparkle-preference/OriWotwRandomizerClient#80]
Coming from the back of this keydoor you approach it while burrowing. This currently prevents you from putting keystones into it
![image](https://user-images.githubusercontent.com/53594055/105715382-d0ff1380-5f1d-11eb-9f40-1a59f2918023.png)

**Comment by MunWolf** [comment]
Marking this as a bug, but technically a new feature.
