### ISSUE TITLE
Invisible Sword in the weapon wheel

### ISSUE THREAD

**Issue by SiriusAshling** [sparkle-preference/OriWotwRandomizerClient#81]
Sometimes in the weapon wheel Sword's icon is invisible. This is purely visual and doesn't affect the player's ability to equip and use it.
![image](https://user-images.githubusercontent.com/53594055/105718791-e6763c80-5f21-11eb-96cd-1b740443c236.png)

**Comment by SiriusAshling** [comment]
This seems to be present only if the player is using Rainy Marsh (and probably before lifting the rain)

**Comment by Foopyo** [comment]
This is now a bigger problem than before because Rainy Marsh is the default state with rust gen.

**Comment by MunWolf** [comment]
Fixed in https://github.com/sparkle-preference/OriWotwRandomizerClient/commit/fa8462def77adaf133b37a4b5590b0984a57451f
