### ISSUE TITLE
Matching shop icons

### ISSUE THREAD

**Issue by SiriusAshling** [sparkle-preference/OriWotwRandomizerClient#87]
If the shops would display correct icons for their randomized items, you wouldn't have to scroll over all the pickups anymore.
It would also be very oriGlow

**Comment by MunWolf** [comment]
This would be hard to do for a lot of the items + our custom upgrades etc so not sure how viable this is

**Comment by MunWolf** [comment]
Scratch that, working on it now

**Comment by timoschwarzer** [comment]
Hmm, the only problem I can see here is that it will be hard for Bingo goals like "Buy THIS from Twillen" since you can't see the icon anymore.

**Comment by SiriusAshling** [comment]
True, those bingo goals should be redesigned as a consequence, to reference things such as "Buy this many from Twillen" or "Spend this much money on Twillen".

I don't think buying a specific Twillen slot is uniquely interesting in a way that has to be preserved over a qol+intuition+flavour win.

Position in shops is ordered by price, not by vanilla positions.

**Comment by MunWolf** [comment]
This has been implemented, bingo goal redesign will have to happen.
