### ISSUE TITLE
Deprecated method used in netcode

### ISSUE THREAD

**Issue by Foopyo** [sparkle-preference/OriWotwRandomizerClient#90]
When the randomizer need to start Discord, it uses the method Buffer which is deprecated and should be replaced by `Buffer.alloc()`, `Buffer.from()` or `Buffer.allocUnsafe()`
![HdgpmQU](https://user-images.githubusercontent.com/25066858/106393882-c353fd00-63f9-11eb-99b6-f9ded26d3116.png)

**Comment by MunWolf** [comment]
Method is used internally by discord SDK, no plans to fix it (other then updating the SDK at some point) closing
